version: "3.7"
services:
  hardhat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FORK=mainnet
    ports:
      - 8545:8545
    command: bin/bash -c "make fork && make deploy"
