[profile.default]
via_ir = false
src = 'contracts'
out = 'foundry_out'
libs = ["foundry_libs"]
test = 'contracts/test'
remappings = [
    'ds-test=foundry_libs/ds-test/src/',
    'forge-std=foundry_libs/forge-std/src/',
]
optimizer = true
optimizer_runs = 19_066
optimizerSteps = ''


