[profile.default]
src = 'contracts/'
out = 'out'
libs = ["lib"]
test = 'test'
ffi = true
remappings = [
  "contracts/=contracts/"
]
ignored_error_codes = [2072, 2059, 5574, 2519, 1878, 5667, 2018, 3445]
fs_permissions = [{ access = "read", path = "./"}]
