name: CI

on:
  push:
    branches:
      - v*
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  run:
    name: Run CI Check
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Check CI
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          make ci
  