name: CI

on:
  push:
    branches:
      - v*
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  tests:
    name: Run CI Check
    runs-on: ubuntu-latest
    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
    steps:
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Check CI
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn
          make ci
  