name: Reusable deployment job

on:
  workflow_call:
    inputs:
      AWS_STACK_NAME:
        type: string
      S3_BUCKET_NAME:
        type: string
      ALTERNATE_DOMAIN_NAME:
        type: string
      CLOUDFLARE_PURGE_URLS:
        type: string
      JS_BUILD_COMMAND:
        type: string
      AWS_REGION:
        default: 'us-east-2'
        type: string
    secrets:
      CERERTIFICATE_ARN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:
        required: true
      CLOUDFLARE_ZONE:
        required: true
      CLOUDFLARE_TOKEN:
        required: true

jobs:
  deploy-s3-and-cloudfront:
    name: Deploy S3 and CloudFront
    runs-on: ubuntu-latest
    outputs:
      CfDistributionId: ${{ steps.cloudformation.outputs.CfDistributionId }}
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Deploy CloudFormation
        id: cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ inputs.AWS_STACK_NAME }}
          template: aws/s3-and-cloudfront-template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            S3BucketName=${{ inputs.S3_BUCKET_NAME }},
            AlternateDomainName=${{ inputs.ALTERNATE_DOMAIN_NAME }},
            CertificateArn=${{ secrets.CERERTIFICATE_ARN }}
  deploy-output-to-s3:
    name: Deploy output files to S3
    needs: deploy-s3-and-cloudfront
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: ${{ inputs.JS_BUILD_COMMAND }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync ./build s3://${{ inputs.S3_BUCKET_NAME }}/ --acl public-read --delete
          aws s3 cp ./build/index.html s3://${{ inputs.S3_BUCKET_NAME }}/ --acl public-read --metadata-directive REPLACE --cache-control "no-store"
      - name: slack
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,eventName,ref,workflow
        if: always()

  clear-cache:
    name: Clear-cache
    needs: [deploy-output-to-s3, deploy-s3-and-cloudfront]
    runs-on: ubuntu-latest
    steps:
      - name: Purge cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          PURGE_URLS: ${{ inputs.CLOUDFLARE_PURGE_URLS }}

      - name: Purge cloudfront cache
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
      - run: aws cloudfront create-invalidation --distribution-id "${{ needs.deploy-s3-and-cloudfront.outputs.CfDistributionId }}" --paths '/*'