name: Verification

on:
  pull_request:
  # workflow_dispatch:
  #   inputs:
  #     network:
  #       description: The EVM compatible network.
  #       default: goerli
  #       required: true
  #     verification:
  #       description: Whether to verify contracts or not.
  #       default: "false"
  #       required: true
  #     verifyContracts:
  #       description: Contracts to be verified on etherscan (separated by comma).
  #       default: "*Logic,Pool*,*Oracle,*Gateway*,*DataProvider,ACLManager,Seaport"
  #       required: true
  #     ref:
  #       description: The deployment commit hash.
  #       required: true
  #     verifyJobs:
  #       description: Number of jobs for verification.
  #       default: "1"
  #       required: true


jobs:
  verification:
    name: Verification
    runs-on: ubuntu-latest
    env:
      # INFURA_KEY: ${{ secrets.INFURA_KEY }}
      # DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      # ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      # CONFIGS_BASE_URL: ${{ secrets.CONFIGS_BASE_URL }}
      # NETWORK: ${{ github.event.inputs.network }}
      # ETHERSCAN_VERIFICATION: ${{ github.event.inputs.verification }}
      # ETHERSCAN_VERIFICATION_CONTRACTS: ${{ github.event.inputs.verifyContracts }}
      # REF: ${{ github.event.inputs.ref }}
      # ETHERSCAN_VERIFICATION_JOBS: ${{ github.event.inputs.verifyJobs }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
      DEPLOYER_MNEMONIC: ${{ secrets.DEPLOYER_MNEMONIC }}
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      CONFIGS_BASE_URL: ${{ secrets.CONFIGS_BASE_URL }}
      NETWORK: "goerli"
      ETHERSCAN_VERIFICATION: "true"
      ETHERSCAN_VERIFICATION_CONTRACTS: "*Logic,Pool*,*Oracle,*Gateway*,*DataProvider,ACLManager,Seaport"
      REF: "72303f98aaf92db2957588245343f0e4a0f1dfda"
      ETHERSCAN_VERIFICATION_JOBS: 4

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          submodules: true
          ref: ${{ env.REF }}

      - name: Use node version 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          yarn cache clean --all
          YARN_CHECKSUM_BEHAVIOR=update yarn
          yarn

      - name: Get deployment date
        id: deploymentInfo
        run: echo ::set-output name=date::$(git show -s --format=%cd --date=format:%m%d ${{ env.REF }})

      - name: Download deployed-contracts.json
        run: |
          curl -H 'Authorization: token ${{ secrets.PAT }}' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -fLo deployed-contracts.json ${{ env.CONFIGS_BASE_URL }}/deployed-contracts.${{  steps.deploymentInfo.outputs.date }}.json

      - name: Verification
        run: |
          echo NETWORK=${{ env.NETWORK }} >> .env
          echo INFURA_KEY=${{ env.INFURA_KEY }} >> .env
          echo DEPLOYER_MNEMONIC=${{ env.DEPLOYER_MNEMONIC }} >> .env
          echo ETHERSCAN_KEY=${{ env.ETHERSCAN_KEY }} >> .env
          echo ETHERSCAN_VERIFICATION=${{ env.ETHERSCAN_VERIFICATION }} >> .env
          echo ETHERSCAN_VERIFICATION_CONTRACTS=${{ env.ETHERSCAN_VERIFICATION_CONTRACTS }} >> .env
          echo ETHERSCAN_VERIFICATION_JOBS=${{ env.ETHERSCAN_VERIFICATION_JOBS }} >> .env
          make verify
